version: '3.9'

services:
  site:
    image: higortupi/site:latest
    ports:
      - "3333:3333"
    depends_on:
      - database
    networks:
      - citrus_network

  java_service:
    image: higortupi/java:latest
    depends_on:
      - database
    networks:
      - citrus_network

  database:
    image: higortupi/db:latest
    environment:
      MYSQL_ROOT_PASSWORD: citrus24vital
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - citrus_network

volumes:
  db_data:

networks:
  citrus_network:
